# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyabc', [dirname(__file__)])
        except ImportError:
            import _pyabc
            return _pyabc
        if fp is not None:
            try:
                _mod = imp.load_module('_pyabc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyabc = swig_import_helper()
    del swig_import_helper
else:
    import _pyabc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def n_ands():
  return _pyabc.n_ands()
n_ands = _pyabc.n_ands

def n_pis():
  return _pyabc.n_pis()
n_pis = _pyabc.n_pis

def n_pos():
  return _pyabc.n_pos()
n_pos = _pyabc.n_pos

def n_latches():
  return _pyabc.n_latches()
n_latches = _pyabc.n_latches

def run_command(*args):
  return _pyabc.run_command(*args)
run_command = _pyabc.run_command

def has_comb_model():
  return _pyabc.has_comb_model()
has_comb_model = _pyabc.has_comb_model

def has_seq_model():
  return _pyabc.has_seq_model()
has_seq_model = _pyabc.has_seq_model

def n_bmc_frames():
  return _pyabc.n_bmc_frames()
n_bmc_frames = _pyabc.n_bmc_frames

def prob_status():
  return _pyabc.prob_status()
prob_status = _pyabc.prob_status

def is_valid_cex():
  return _pyabc.is_valid_cex()
is_valid_cex = _pyabc.is_valid_cex

def is_true_cex():
  return _pyabc.is_true_cex()
is_true_cex = _pyabc.is_true_cex

def n_cex_pis():
  return _pyabc.n_cex_pis()
n_cex_pis = _pyabc.n_cex_pis

def n_cex_regs():
  return _pyabc.n_cex_regs()
n_cex_regs = _pyabc.n_cex_regs

def cex_po():
  return _pyabc.cex_po()
cex_po = _pyabc.cex_po

def cex_frame():
  return _pyabc.cex_frame()
cex_frame = _pyabc.cex_frame

def n_phases():
  return _pyabc.n_phases()
n_phases = _pyabc.n_phases

def pyabc_internal_set_command_callback(*args):
  return _pyabc.pyabc_internal_set_command_callback(*args)
pyabc_internal_set_command_callback = _pyabc.pyabc_internal_set_command_callback

def pyabc_internal_register_command(*args):
  return _pyabc.pyabc_internal_register_command(*args)
pyabc_internal_register_command = _pyabc.pyabc_internal_register_command
_registered_commands = {}

def _cmd_callback(args):
	try:
	    assert len(args) > 0
	    
	    cmd = args[0]
	    assert cmd in _registered_commands
	
	    res = _registered_commands[cmd](args)
	    
	    assert type(res) == int, "User-defined Python command must return an integer."
	    
	    return res
	
	except Exception, e:
		print "Python error: ", e

	except SystemExit, se:
		pass
		
	return 0
    
pyabc_internal_set_command_callback( _cmd_callback )
    
def add_abc_command(fcmd, group, cmd, change):
    _registered_commands[ cmd ] = fcmd
    pyabc_internal_register_command( group, cmd, change)

import sys
import optparse

import __main__

def cmd_python(cmd_args):
    global __main__
    
    usage = "usage: %prog [options] <Python files>"
    
    parser = optparse.OptionParser(usage)
    
    parser.add_option("-c", "--cmd", dest="cmd", help="Execute Python command directly")
    parser.add_option("-v", "--version", action="store_true", dest="version", help="Display Python Version")

    options, args = parser.parse_args(cmd_args)
    
    if options.version:
        print sys.version
        return 0
    
    if options.cmd:
        exec options.cmd in __main__.__dict__
        return 0
    
    for fname in args[1:]:
        execfile(fname, __main__.__dict__)
    
    return 0
    
add_abc_command(cmd_python, "Python", "python", 0) 




